### ISSUE TITLE
Possible to ignore certain variables?

### ISSUE THREAD

**Issue by bitbythecron** [pledbrook/lazybones#191]
Any recommendations/hacks/workaround for when the post-templated file needs to have `${...}`-style tokens in it that should be _ignored_ by lazybones?

For example, a sample `application.yml` file for a Spring Boot app:

```
logging:
  config: 'logback.groovy'
${appname}:
  configWaitForAnswerMillis: ${configTime}
```

Say I want lazybones to replace `${appname}` with the name of the app I'm generating, but I want lazybones to ignore `${configTime}` so that the resultant YAML file might look like:

```
logging:
  config: 'logback.groovy'
myapp:
  configWaitForAnswerMillis: ${configTime}
```

Any suggestions here? Thanks!
